//auth constants
export const POST_SIGNUP = 'POST_SIGNUP';
export const POST_SIGNIN = 'POST_SIGNIN';
export const GET_VERIFY_NICKNAME = 'GET_VERIFY_NICKNAME';
export const RESET_VERIFY_NICKNAME = 'RESET_VERIFY_NICKNAME';
export const RESET_SIGNIN = 'RESET_SIGNIN';

//contact constants
export const POST_ADD_CONTACT = 'POST_ADD_CONTACT';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';
export const GET_CONTACTS = 'GET_CONTACTS';
export const RESET_ADD_CONTACT = 'RESET_ADD_CONTACT';
export const RESET_GET_CONTACTS = 'RESET_GET_CONTACTS';

//conersation constants
export const SET_CURRENT_CONVERSATION = 'SET_CURRENT_CONVERSATION';
export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const SET_CURRENT_CONVERSATION_MESSAGES = 'SET_CURRENT_CONVERSATION_MESSAGES';
export const ADD_MESSAGE_TO_CURRENT_CONVERSATION_MESSAGES = 'ADD_MESSAGE_TO_CURRENT_CONVERSATION_MESSAGES';
export const INCREMENT_CONVERSATION_UNREAD_MESSAGES = 'INCREMENT_CONVERSATION_UNREAD_MESSAGES';
export const RESET_CONVERSATION_UNREAD_MESSAGES = 'RESET_CONVERSATION_UNREAD_MESSAGES';
export const DELETE_CONVERSATION = 'DELETE_CONVERSATION';
export const REMOVE_CONVERSATION = 'REMOVE_CONVERSATION';
export const REMOVE_MESSAGE_FROM_CONVERSATION = 'REMOVE_MESSAGE_FROM_CONVERSATION';

//drwaer constants
export const OPEN_DRAWER = 'OPEN_DRAWER';
export const CLOSE_DRAWER = 'CLOSE_DRAWER';
export const INIT_DRAWER = 'INIT_DRAWER';

//form constants
export const INIT_FORM = 'INIT_FORM';
export const UPDATE_FORM = 'UPDATE_FORM';
export const SET_FORM_ERROR = 'SET_FORM_ERROR';

//main constant
export const RESET = 'RESET';

//message constants
export const POST_MESSAGE = 'POST_MESSAGE';
export const GET_MESSAGES = 'GET_MESSAGES';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';


//socket constants
export const START_CHANNEL = 'START_CHANNEL';
export const STOP_CHANNEL = 'STOP_CHANNEL';
export const SERVER_ON = 'SERVER_ON';
export const SERVER_OFF = 'SERVER_OFF';